import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:tendria/features/user/presentation/controller/profile_controller.dart';

class LanguageController extends GetxController {
  String get deviceLanguage => _deviceLanguage;

  String get _deviceLanguage {
    final locale = WidgetsBinding.instance.platformDispatcher.locale;
    final languageCode = locale.languageCode;

    if (languageCode == 'es') return 'Español';
    if (languageCode == 'en') return 'Inglés';

    return 'Inglés';
  }

  String get lang {
    try {
      final profileLang = Get.find<ProfileController>().primarylanguage;
      if (_translations.containsKey(profileLang)) {
        return profileLang;
      }
      return _deviceLanguage;
    } catch (_) {
      return _deviceLanguage;
    }
  }

  String t(String key) => translate(key, lang);

  String translate(String key, String language) {
    return _translations[language]?[key] ??
        _translations['Español']?[key] ??
        key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'Español': {
      // ── UpdateProfilePage ──────────────────────────
      'age_range': 'Rango de edad',
      'max_distance': 'Distancia máxima',
      'height': 'Altura',
      'my_gender': 'Mi Género',
      'language': 'Idioma',
      'birth_date': 'Fecha de nacimiento',
      'looking_for': 'Busco',
      'connection_type': 'Tipo de conexión',
      'delete_account': 'Eliminar cuenta',
      'no_limit': 'Máximo',
      "bs_no_numbers": "no puede contener números",

      // ── ProfilePage ────────────────────────────────
      'profile': 'Perfil',
      'discover': 'Descubrir perfiles cercanos',
      'photos': 'Fotos',
      'photos_hint': 'Toca + para agregar varias fotos de jalón',
      'my_biography': 'Mi Biografía',
      'add_status': 'Agregar estado',

      // ── LikedByUsersView ───────────────────────────
      'pending_chats': 'Match Pendientes',
      'unlock_hint': 'Desbloquea los chats para comenzar a conversar.',
      'unlock': 'Desbloquear',
      'connect': 'Conectar',

      // ── RadarScannerScreen ─────────────────────────
      'searching': 'Buscando conexiones...',
      'nearby': 'Perfiles que están cerca de ti',
      'search_btn': 'Buscar Perfiles Cercanos',
      'view_profile': 'Ver mi perfil',
      'travel_mode_active': 'Modo viaje activo',
      'travel_mode_active_desc': 'Estás viendo perfiles de otra ciudad',
      'travel_mode_deactivated': 'Modo viaje desactivado',
      'deactivate': 'Desactivar',
      'search_city_title': 'Buscar ciudad',
      'search_city_hint': 'Escribe el nombre de una ciudad...',
      'search_city_prompt': 'Escribe para buscar ciudades',
      'search_city_no_results': 'Sin resultados',
      'search_city_btn': 'Buscar en otra ciudad',
      'city_updated': 'Ciudad actualizada',
      // ── MyMatchView ────────────────────────────────
      'stories': 'Historias',
      'my_story': 'Mi historia',
      'chats': 'Chats',
      'no_reply': 'Sin responder',
      'filter_chats': 'Filtrar chats',
      'filter_no_reply': 'Sin responder',
      'filter_no_reply_desc': 'Solo chats donde esperan tu respuesta',
      'clear_filters': 'Limpiar filtros',
      'search_hint': 'Buscar chats...',
      'your_turn': 'Tu turno',
      'start_chat': '¡Comienza a chatear!',
      'all_caught_up': '¡Todo al día! No tienes chats pendientes de respuesta',
      'see_all': 'Ver todos los chats',

      // ── InterestsSectionWidget ─────────────────────
      'interests_title': 'Intereses',
      'interests_subtitle': 'Muestra las cosas que te encantan',
      'interests_add': 'Agrega tus intereses',

      // ── QualitiesSectionWidget ─────────────────────
      'qualities_title': 'Cualidades que valoro',
      'qualities_subtitle':
          'Elige hasta 3 cualidades que valoras en una persona.',
      'qualities_add': 'Agrega cualidades que valoras',

      // ── Bottom sheets: Intereses ───────────────────
      'bs_interests_title': 'Elige tus intereses\nprincipales',
      'bs_interests_subtitle':
          'Tus gustos nos ayudan a encontrar mejores coincidencias.',
      'bs_interests_counter': 'Intereses populares',
      'bs_interests_selected': 'seleccionados',
      'bs_max_interests': 'Puedes seleccionar máximo 5 intereses',
      'bs_interests_saved': 'Intereses actualizados correctamente',
      'bs_interests_load_error': 'No se pudieron cargar los intereses',

      // ── Bottom sheets: Cualidades ──────────────────
      'bs_qualities_title': 'Lo que más aprecias en\nuna persona',
      'bs_qualities_subtitle':
          'Estas cualidades nos ayudan a crear mejores coincidencias.',
      'bs_qualities_counter': 'Lo que buscas en alguien',
      'bs_max_qualities': 'Puedes seleccionar máximo 3 cualidades',
      'bs_qualities_saved': 'Cualidades actualizadas correctamente',

      // ── Bottom sheets: Altura ──────────────────────
      'bs_height_title': 'Tu altura',
      'bs_height_subtitle':
          'Esta información nos ayuda a mejorar tus coincidencias.',

      // ── Bottom sheets: Género ──────────────────────
      'bs_gender_title': '¿Cuál es tu género?',
      'bs_gender_subtitle': 'Esta información es editable más adelante.',

      // ── Bottom sheets: Idioma ──────────────────────
      'bs_language_title': 'Tu idioma principal',
      'bs_language_subtitle': 'Puedes ajustar esto más tarde.',

      // ── Bottom sheets: Fecha nacimiento ───────────
      'bs_dob_title': 'Fecha de nacimiento',
      'bs_dob_subtitle': 'Debes ser mayor de 18 años.',
      'bs_dob_age_error': 'Debes tener al menos 18 años para registrarte.',

      // ── Bottom sheets: Busco ───────────────────────
      'bs_search_gender_title': '¿Qué tipo de personas te\ngustaría conocer?',
      'bs_search_gender_subtitle':
          'Esta preferencia es flexible y editable más adelante.',

      // ── Bottom sheets: Tipo de conexión ───────────
      'bs_connection_title': '¿Qué tipo de conexión\nquieres?',
      'bs_connection_subtitle': 'Selecciona la opción que vaya contigo.',

      // ── Bottom sheets: Rango de edad ──────────────
      'bs_age_range_title': 'Rango de edad',
      'bs_age_min': 'Mínimo',
      'bs_age_max': 'Máximo',

      // ── Bottom sheets: Distancia ───────────────────
      'bs_distance_title': 'Distancia máxima',
      'bs_no_limit_distance': 'Distancia máxima',

      // ── Bottom sheets: Biografía ───────────────────
      'bs_bio_title': 'Cuéntanos sobre ti',
      'bs_bio_subtitle':
          'Una buena biografía ayuda a generar mejores conexiones.',
      'bs_bio_hint': 'Escribe algo sobre ti...',

      // ── Bottom sheets: Estado ──────────────────────
      'bs_status_title': 'Tu estado',
      'bs_status_subtitle': 'Un estado corto que refleje cómo te sientes hoy.',
      'bs_status_hint': 'Ej: Buscando aventuras...',

      // ── Snackbars generales ────────────────────────
      'snack_no_changes': 'No hay cambios nuevos',
      'snack_updated': 'Actualizado correctamente',
      'snack_height_saved': 'Altura actualizada',
      'snack_gender_saved': 'Género actualizado',
      'snack_language_saved': 'Idioma actualizado',
      'snack_dob_saved': 'Fecha de nacimiento actualizada',
      'snack_search_gender_saved': 'Preferencia actualizada',
      'snack_connection_saved': 'Tipo de conexión actualizado',
      'snack_age_range_saved': 'Rango de edad actualizado',
      'snack_distance_saved': 'Distancia actualizada',
      'snack_bio_saved': 'Biografía actualizada',
      'snack_status_saved': 'Estado actualizado',
      'snack_interest_removed': 'Interés eliminado correctamente',
      'snack_quality_removed': 'Cualidad eliminada correctamente',
      'snack_photo_added': 'Tu foto se ha agregado correctamente',
      'snack_photo_removed': 'La foto se ha eliminado correctamente',
      'snack_could_not_update': 'No se pudo actualizar',
      'snack_could_not_delete': 'No se pudo eliminar',
      'snack_could_not_save_interests': 'No se pudieron guardar los intereses',
      'snack_could_not_save_qualities': 'No se pudieron guardar las cualidades',

      // ── Alertas generales ──────────────────────────
      'alert_delete_photo_title': 'Eliminar foto',
      'alert_delete_photo_msg': '¿Estás seguro que deseas eliminar esta foto?',
      'alert_logout_title': 'Cerrar sesión',
      'alert_logout_msg': '¿Estás seguro que deseas cerrar sesión?',
      'alert_delete_account_title': 'Eliminar cuenta',
      'alert_delete_account_msg':
          '¿Estás seguro? Esta acción es permanente y no se puede deshacer.',
      'alert_confirm': 'Aceptar',
      'alert_delete': 'Eliminar',

      // ── Compartidas ────────────────────────────────
      'years': 'años',
      'user': 'Usuario',
      'loading': 'Cargando...',
      'loading_chats': 'Cargando chats...',
      'loading_pending': 'Cargando chats pendientes...',
      'error_title': 'Error al cargar chats',
      'retry': 'REINTENTAR',
      'empty_title_chats': 'No tienes chats aún',
      'empty_subtitle_chats':
          'Comienza a dar likes para encontrar tu match perfecto',
      'empty_title_pending': 'No tienes match pendientes',
      'empty_subtitle_pending': 'Cuando alguien te escriba, aparecerá aquí',
      'explore': 'EXPLORAR PERFILES',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'error': 'Error',
      'accept': 'Aceptar',

      'no_more_profiles': 'No hay más perfiles',
      'no_more_profiles_desc':
          'No encontramos perfiles que coincidan con tus filtros actuales. Amplía tu rango de búsqueda para ver más personas.',
      'modify_preferences': 'Modificar preferencias',
      'try_again': 'Intentar de nuevo',

      // ── RegisterPage ───────────────────────────────
      'register_title': 'Empezar',
      'register_have_account': '¿Ya cuentas con un registro? ',
      'register_login': 'Iniciar Sesión',
      'register_name': 'Nombre Completo:',
      'register_name_hint': 'Karen Hernández Costa',
      'register_email': 'Correo electrónico:',
      'register_email_hint': 'correo@gmail.com',
      'register_password': 'Crea una contraseña',
      'register_confirm_password': 'Confirma tu contraseña:',
      'register_privacy':
          'Al registrarte estas aceptando el Aviso de Privacidad y los Términos y Condiciones.',
      'register_btn': 'Registrarse',

      'personal_title': 'Iniciemos con lo\nbásico',
      'personal_dob': 'Selecciona tu fecha de nacimiento',
      'personal_dob_placeholder': '14/05/1993',
      'personal_gender': '¿Cómo te identificas?',
      'personal_bio': 'Cuéntanos sobre ti:',
      'personal_bio_hint': 'Escribe una breve biografía...',

      'physical_title':
          'Esta información nos ayuda a\nmejorar tus coincidencias',
      'physical_height': 'Tu altura',

      'interests_page_title': 'Elige tus intereses\nprincipales',
      'interests_page_subtitle':
          'Tus gustos nos ayudan a encontrar mejores\ncoincidencias.',
      'interests_search_hint': 'Buscar intereses',
      'interests_popular': 'Intereses populares',
      'interests_custom_hint':
          'si no se encuentran tus resultados escríbelos...',

      'qualities_page_title': 'Lo que más aprecias en una\npersona',
      'qualities_page_subtitle':
          'Estas cualidades nos ayudan a crear mejores\ncoincidencias.',
      'qualities_counter_label': 'Lo que buscas en alguien',

      'nav_skip': 'Omitir',
      'login_title': 'Iniciar Sesión',
      'login_no_account': '¿Aún no tienes una cuenta? ',
      'login_register': 'Registrarse',
      'login_email': 'Correo electrónico:',
      'login_email_hint': 'correo@gmail.com',
      'login_password': 'Contraseña:',
      'login_remember': 'Recuérdame',
      'login_btn': 'Iniciar Sesión',
      'login_forgot': '¿Olvidaste tu contraseña?',
      'forgot_title': 'Recupera tu contraseña',
      'forgot_step1': 'Escribe tu correo y te enviaremos un código de 6 dígitos.',
      'forgot_step2': 'Revisa tu correo, escribe el código y elige una contraseña nueva.',
      'forgot_code': 'Código',
      'forgot_new_password': 'Contraseña nueva',
      'forgot_send_btn': 'Enviar código',
      'forgot_change_btn': 'Cambiar contraseña',
      'forgot_resend': 'Reenviar código',
      'forgot_code_sent': 'Si el correo existe, te enviamos un código',
      'forgot_done': 'Contraseña actualizada. Ya puedes iniciar sesión',
      'forgot_err_email': 'Escribe un correo válido',
      'forgot_err_code': 'El código tiene 6 dígitos',
      'forgot_err_password': 'La contraseña debe tener al menos 8 caracteres',

      'val_name_required': 'El nombre es requerido',
      'val_name_min': 'Mínimo 3 caracteres',
      'val_email_required': 'El correo es requerido',
      'val_email_invalid': 'Ingresa un correo válido',
      'val_password_required': 'La contraseña es requerida',
      'val_min_8': 'Mínimo 8 caracteres',
      'val_min_10': 'Mínimo 10 caracteres',
      'val_max_500': 'Máximo 500 caracteres',
      'val_passwords_no_match': 'Las contraseñas no coinciden',
      'val_dob_required': 'Selecciona tu fecha de nacimiento',
      'val_gender_required': 'Selecciona tu género',
      'val_custom_gender_required': 'Escribe cómo te identificas',
      'val_bio_required': 'La biografía es requerida',
      'val_bio_min': 'La biografía debe tener al menos 10 caracteres',
      'val_bio_max': 'La biografía debe tener máximo 500 caracteres',
      'val_height_required': 'Ingresa tu altura',
      'val_height_invalid': 'Ingresa una altura válida entre 100 y 250 cm',
      'val_interest_required': 'Selecciona al menos un interés',
      'val_max_interests': 'Solo puedes seleccionar hasta',
      'val_max_qualities': 'Solo puedes seleccionar hasta',
      'register_success': 'Registro exitoso. Por favor, inicia sesión.',

      'login_warning': 'Advertencia',
      'login_val_email': 'Por favor, ingresa tu correo',
      'login_val_password': 'Por favor, ingresa tu contraseña',
      'login_error_title': 'Acceso incorrecto',
      'chat_reconnecting': 'Reconectando...',
      'chat_no_connection': 'Sin conexión · Toca para reintentar',
      'chat_cost_info': 'Este mensaje tiene un costo de ',
      'chat_balance_info': 'Tus créditos actuales son de ',
      'chat_charge_info': 'El mensaje se cobrará solo cuando se envíe.',
      'chat_first_msg_sent': 'Primer mensaje enviado. Espera la respuesta.',
      'followers': 'seguidores',
      'following': 'siguiendo',
      'follow_btn': 'Seguir',
      'following_btn': 'Siguiendo',
      'feed_title': 'Feed',
      'feed_new_post': 'Publicar',
      'feed_write': '¿Qué quieres compartir?',
      'feed_publish': 'Publicar',
      'feed_add_photo': 'Fotos',
      'feed_add_video': 'Video',
      'feed_comments': 'Comentarios',
      'feed_comment_hint': 'Escribe un comentario…',
      'feed_reply': 'Responder',
      'feed_replying_to': 'Respondiendo a',
      'feed_delete': 'Eliminar',
      'feed_report': 'Reportar',
      'feed_reported': 'Gracias, revisaremos este contenido',
      'feed_deleted': 'Publicación eliminada',
      'feed_video_too_long': 'El video debe durar máximo 60 segundos',
      'feed_video_too_big': 'El video debe pesar máximo 50 MB',
      'feed_max_media': 'Máximo 10 archivos por publicación',
      'feed_user_posts': 'Publicaciones',
      'feed_no_comments': 'Sé el primero en comentar',
      'feed_react': 'Reaccionar',
      'feed_confirm_delete': '¿Eliminar esta publicación?',
      'feed_load_more': 'Ver más',
      'feed_retry': 'Reintentar',
      'feed_empty_title': 'Tu feed está vacío',
      'feed_empty': 'Sigue a personas para ver lo que comparten o comparte algo tú.',
      'feed_empty_user': 'Aún no hay publicaciones',
      'feed_discover': 'Descubrir personas',
      'feed_create_first': 'Crear mi primera publicación',
      'feed_see_more': 'más',
      'feed_view_all': 'Ver los',
      'feed_view_one': 'Ver 1 comentario',
      'feed_audience': 'Tus seguidores',
      'feed_create_title': 'Nueva publicación',
      'gift_send_title': 'Enviar un regalo',
      'gift_to': 'para',
      'gift_send_btn': 'Enviar',
      'gift_credits': 'créditos',
      'gift_pick': 'Elige un regalo',
      'gift_recharge': 'Recargar créditos',
      'gift_sent': '¡Regalo enviado!',
      'gift_pill': 'Regalo',
      'gift_received_title': 'Regalos recibidos',
      'gift_you_sent': 'Enviaste un regalo',
      'gift_sent_to_you': 'Te envió un regalo',
      'plans_title': 'Planes',
      'my_credits': 'Mis créditos',
      'chat_online': 'En línea',
      'chat_last_seen': 'Últ. vez',
      'profile_posts_short': 'Posts',
      'gift_recharge_short': 'Recargar',
      'profile_followers': 'Seguidores',
      'profile_following': 'Siguiendo',
      'profile_gifts': 'Regalos',
      'profile_connections': 'Conexiones',
      'profile_no_posts': 'Aún no hay publicaciones',
      'profile_no_posts_own': 'Todavía no has publicado nada. ¡Comparte tu primera foto o pensamiento!',
      'profile_no_plans': 'Sin planes por ahora',
      'profile_no_plans_own': 'Aún no tienes planes. Crea uno o únete a alguno.',
      'profile_no_communities': 'No pertenece a comunidades públicas',
      'profile_no_communities_own': 'Aún no te unes a ninguna comunidad',
      'profile_no_gifts': 'Todavía no ha recibido regalos',
      'profile_no_gifts_own': 'Aún no has recibido regalos',
      'profile_see_all_posts': 'Ver todas las publicaciones',
      'profile_see_all_plans': 'Ver todos mis planes',
      'follow_list_empty_followers': 'Aún no hay seguidores',
      'follow_list_empty_following': 'Aún no sigue a nadie',
      'feed_filter_communities': 'Comunidades',
      'community_my': 'Mis comunidades',
      'community_new': 'Nueva',
      'community_empty': 'Aún no hay comunidades. ¡Crea la primera y reúne a tu gente!',
      'community_create': 'Crear comunidad',
      'community_create_btn': 'Crear comunidad',
      'community_f_name': 'Nombre de la comunidad',
      'community_f_name_hint': 'Ej. Amantes del senderismo',
      'community_f_description_hint': 'De qué trata y qué reglas tiene…',
      'community_f_city': 'Ciudad (opcional)',
      'community_f_city_hint': 'Ej. Guadalajara',
      'community_private': 'Comunidad privada',
      'community_private_hint': 'Entran con tu aprobación y solo los miembros ven el contenido',
      'community_public_hint': 'Cualquiera puede unirse y ver el contenido',
      'community_add_cover': 'Agregar portada',
      'community_err_name': 'El nombre debe tener al menos 3 letras',
      'community_members': 'Miembros',
      'community_joined': 'Miembro',
      'community_role_admin': 'Admin',
      'community_role_moderator': 'Moderador',
      'community_locked': 'Esta comunidad es privada. Solicita unirte para ver sus publicaciones y miembros.',
      'community_no_posts': 'Aún no hay publicaciones. ¡Sé la primera persona en publicar!',
      'community_no_requests': 'No hay solicitudes pendientes',
      'community_make_admin': 'Hacer administrador',
      'community_make_moderator': 'Hacer moderador',
      'community_make_member': 'Quitar rol',
      'community_kick': 'Expulsar de la comunidad',
      'community_leave': 'Salir de la comunidad',
      'community_post_here': 'Publicar en la comunidad',
      'community_post_in': 'Publicar en',
      'community_delete': 'Eliminar comunidad',
      'community_delete_confirm': '¿Eliminar esta comunidad?',
      'community_delete_hint': 'Se ocultarán la comunidad y todas sus publicaciones. No se puede deshacer.',
      'community_cat_gaming': 'Gaming',
      'community_cat_fitness': 'Fitness',
      'community_cat_viajes': 'Viajes',
      'community_cat_musica': 'Música',
      'community_cat_deportes': 'Deportes',
      'community_cat_fotografia': 'Fotografía',
      'community_cat_cocina': 'Cocina',
      'community_cat_arte': 'Arte',
      'community_cat_tecnologia': 'Tecnología',
      'community_cat_local': 'Local',
      'community_cat_otro': 'Otro',
      'feed_filter_all': 'Todo',
      'feed_filter_posts': 'Publicaciones',
      'feed_filter_plans': 'Planes',
      'plans_discover': 'Descubrir',
      'plans_mine': 'Mis planes',
      'plans_create': 'Crear plan',
      'plans_all': 'Todos',
      'plans_empty_discover': 'Aún no hay planes próximos. ¡Crea el primero!',
      'plans_empty_mine': 'Todavía no tienes planes. Únete a uno o crea el tuyo.',
      'plans_upcoming': 'Próximos',
      'plans_past': 'Pasados',
      'plan_months': 'ene,feb,mar,abr,may,jun,jul,ago,sep,oct,nov,dic',
      'plan_weekdays': 'lun,mar,mié,jue,vie,sáb,dom',
      'plan_cat_salidas': 'Salidas',
      'plan_cat_cine': 'Cine',
      'plan_cat_senderismo': 'Senderismo',
      'plan_cat_viajes': 'Viajes',
      'plan_cat_deportes': 'Deportes',
      'plan_cat_gaming': 'Gaming',
      'plan_cat_restaurantes': 'Restaurantes',
      'plan_cat_conciertos': 'Conciertos',
      'plan_cat_reuniones': 'Reuniones',
      'plan_cat_social': 'Social',
      'plan_cat_otro': 'Otro',
      'plan_cancelled': 'Plan cancelado',
      'plan_going': 'van',
      'plan_yours': 'Tu plan',
      'plan_you_go': 'Vas',
      'plan_pending': 'Pendiente',
      'plan_full': 'Lleno',
      'plan_cancel_confirm': '¿Cancelar este plan?',
      'plan_cancel_hint': 'Se avisará a quienes se habían unido.',
      'plan_cancel_action': 'Cancelar plan',
      'plan_needs_approval': 'Con aprobación',
      'plan_needs_approval_hint': 'Tú decides quién se une',
      'plan_open': 'Abierto para todos',
      'plan_organizer': 'Organiza',
      'plan_going_title': 'Van',
      'plan_requests': 'Solicitudes',
      'plan_finished': 'Este plan ya terminó',
      'plan_leave': 'Salir del plan',
      'plan_cancel_request': 'Cancelar solicitud',
      'plan_rejected': 'Solicitud no aceptada',
      'plan_request': 'Solicitar unirme',
      'plan_join': 'Unirme',
      'plan_f_title': 'Nombre del plan',
      'plan_f_title_hint': 'Ej. Cine y palomitas',
      'plan_f_category': 'Categoría',
      'plan_f_when': 'Cuándo',
      'plan_f_date': 'Fecha',
      'plan_f_time': 'Hora',
      'plan_f_place': 'Lugar',
      'plan_f_place_hint': 'Ej. Cinépolis Centro',
      'plan_use_location': 'Usar mi ubicación actual',
      'plan_f_description': 'Descripción',
      'plan_f_description_hint': 'Cuenta de qué trata el plan…',
      'plan_f_capacity': 'Cupo',
      'plan_unlimited': 'Sin límite de personas',
      'plan_f_capacity_hint': 'Máximo de personas (2 a 500)',
      'plan_publish': 'Publicar plan',
      'plan_add_cover': 'Agregar portada',
      'plan_location_denied': 'Permiso de ubicación denegado',
      'plan_location_set': 'Ubicación agregada',
      'plan_err_title': 'Escribe un nombre para el plan (mínimo 3 letras)',
      'plan_err_datetime': 'Elige fecha y hora',
      'plan_err_place': 'Indica el lugar del plan',
      'plan_err_future': 'La fecha y hora deben ser futuras',
      'plan_err_capacity': 'El cupo debe estar entre 2 y 500 personas',
      'chat_hint_blocked': 'Espera la respuesta...',
      'chat_hint': 'Escribe un mensaje...',
      'chat_empty_title': 'Inicia la conversación',
      'chat_empty_subtitle': 'Envía el primer mensaje para comenzar',
      'chat_error_title': 'Error al cargar mensajes',
      'nearby_no_more': 'No hay más usuarios cercanos',
      'nearby_load_error': 'No se pudieron cargar los usuarios',
      'nearby_liked': '¡Te gusta',
      'nearby_removed_fav': 'removido de favoritos',
      'nearby_error_process': 'Error al procesar',
      'nearby_like_sent': '¡Le diste like a',
      'nearby_error_like': 'Error al dar like',
      'nearby_next_profile': 'Pasando al siguiente perfil',
      'nearby_error_reject': 'Error al rechazar',
      'nearby_superlike_sent': 'Le has enviado un Super Like a',
      'nearby_block_title': 'Bloquear usuario',
      'nearby_block_msg': '¿Estás seguro de que quieres bloquear a',
      'nearby_block_confirm': 'Bloquear',
      'nearby_blocked': 'ha sido bloqueado',
      'nearby_all_seen': 'Has visto todos los perfiles disponibles',
      'nearby_report_title': 'Reportar usuario',
      'nearby_report_msg': '¿Por qué quieres reportar a',
      'nearby_report_confirm': 'Reportar',
      'nearby_report_thanks':
          'Gracias por tu reporte. Revisaremos el perfil de',
      'nearby_send_message': 'Enviar mensaje',
      'nearby_view_profile': 'Ver perfil completo',
      'chat_credits': 'créditos',
      'location_required_title': 'Ubicación requerida',
      'location_required_desc':
          'Necesitamos tu ubicación para mostrarte usuarios cercanos',
      'enable_location': 'Activar ubicación',
      'open_settings': 'Abrir configuración',
      //PreferencesPage
      'pref_gender_title': '¿Qué tipo de personas te\ngustaría conocer?',
      'pref_gender_subtitle':
          'Esta preferencia es flexible y editable más adelante.',
      'pref_gender_hint':
          'Te mostraremos perfiles compatibles con tus preferencias.',
      'pref_connection_title': '¿Qué tipo de conexión\nquieres?',
      'pref_connection_subtitle':
          'Selecciona hasta dos opciones que vayan contigo.',
      'pref_connection_hint':
          'Mostraremos esta preferencia para mejorar tus coincidencias.',
      'pref_age_title': '¿Qué rango de edad\nprefieres?',
      'pref_age_subtitle': 'Puedes ajustar esto más tarde.',
      'pref_distance_title': 'Distancia máxima',
      'pref_distance_up_to': 'Hasta',
      'pref_photos_title': 'Preséntate con fotos',
      'pref_photos_subtitle':
          'Sube al menos 2 fotos que muestren tu esencia.\nLas mejores conexiones empiezan con buenas fotos.',
      'pref_selection_required': 'Selección requerida',
      'pref_select_gender': 'Selecciona un tipo de persona',
      'pref_select_connection': 'Selecciona al menos un tipo de conexión',
      'pref_invalid_range': 'Rango inválido',
      'pref_age_range_error':
          'La edad mínima no puede ser mayor que la edad máxima',
      'pref_photos_required': 'Fotos requeridas',
      'pref_photos_min': 'Debes subir al menos 2 fotos',
      'pref_interests_required': 'Intereses requeridos',
      'pref_qualities_required': 'Cualidades requeridas',
      'pref_select_quality': 'Debes seleccionar al menos una cualidad',
      'pref_limit_reached': 'Límite alcanzado',

      'pref_no_interests': 'No hay intereses disponibles',
      'pref_no_qualities': 'No hay cualidades disponibles',

      'pref_photos_max': 'Puedes subir máximo',
      'pref_photos_partial': 'Solo se agregaron',
      'pref_photos_pick_error': 'No se pudo seleccionar la foto',
      'pref_photo_take_error': 'No se pudo tomar la foto',
      'pref_add_photos': 'Agregar fotos',
      'pref_gallery_multiple': 'Galería (selección múltiple)',
      'pref_gallery_multiple_hint': 'Selecciona varias fotos de jalón',
      'pref_take_photo': 'Tomar foto',
      'pref_take_photo_hint': 'Captura una nueva foto',

      // ── Tutoriales ─────────────────────────────────
      'tutorial_start_profile':
          'Aquí puedes ver y editar la información de tu perfil',
      'tutorial_start_radar':
          'Radar: encuentra personas cercanas a tu ubicación',
      'tutorial_start_match':
          'Match: ve las personas que quieren conectar contigo',
      'tutorial_start_chat': 'Chat: sigue la conversación con tus conexiones',
      'tutorial_start_panic':
          'Botón de pánico: en caso de emergencia presionalo para llamar al 911 y pedir ayuda inmediata',

      'tutorial_profile_blocked':
          'Aquí puedes ver y gestionar los usuarios que has bloqueado',
      'tutorial_profile_notifications':
          'Gestiona tus notificaciones push y preferencias de alertas',
      'tutorial_profile_edit':
          'Edita tu perfil: nombre, edad, preferencias y más',
      'tutorial_profile_settings': 'opción para cerrar sesión',
      'tutorial_profile_credits':
          'Toca aquí para agregar más créditos a tu cuenta',
      'tutorial_profile_status':
          'Toca para editar tu mensaje de estado visible en el radar',

      'tutorial_update_age':
          'Edita el rango de edad de las personas con quienes prefieres conectar',
      'tutorial_update_distance':
          'Ajusta la distancia máxima de las personas con las que prefieres conectar',

      'tutorial_radar_slider':
          'Ajusta el radio de búsqueda para encontrar personas más cerca o más lejos de ti',
      'tutorial_radar_points':
          'Te damos un grupo pequeño de perfiles cercanos para que puedas ver a cada persona',
      'tutorial_radar_search': 'Vuelve a pulsar para ver más',
      'tutorial_radar_profile': 'Pulsa para ver los perfiles',
      'tutorial_skip': 'Omitir',

      // ── LikedByUsersView ───────────────────────────
      'liked_by_title': 'Les gusté',
      'liked_by_hint': 'Usuarios que te dieron like',
      'liked_by_tab': 'Les gusté',
      'pending_tab': 'Pendientes',
      'liked_by_view_profile': 'Ver perfil',
      'liked_by_empty_title': 'Nadie te ha dado like aún',
      'liked_by_empty_subtitle': 'Sigue explorando para conseguir más matches',
      'liked_by_error_title': 'Error al cargar likes',
      'liked_by_loading': 'Cargando likes...',

      //reportar
      'report_title': 'Reportar a',
      'report_select_reason': 'Selecciona el motivo del reporte',
      'report_harassment': 'Acoso o intimidación',
      'report_inappropriate': 'Contenido inapropiado',
      'report_fake': 'Perfil falso o spam',
      'report_offensive': 'Comportamiento ofensivo',
      'report_minor': 'Menor de edad',
      'report_other': 'Otro',
      'report_desc_hint': 'Descripción (requerida)',
      'report_desc_required': 'La descripción es requerida',
      'report_also_block': 'También bloquear a',
      'report_block_hint': 'No podrá contactarte ni ver tu perfil',
      'report_send': 'Enviar reporte',
      'report_send_and_block': 'Reportar y bloquear',
      'report_success': 'Reporte enviado. Revisaremos el perfil  de',
      'report_block_success': 'ha sido reportado y bloqueado',
      //SelfieCameraResult
      'selfie_place_face': 'Coloca tu rostro en el círculo',
      'selfie_face_detected': 'Rostro detectado, mantente quieto...',
      'selfie_no_move_3': '¡No te muevas! Tomando foto en 3...',
      'selfie_no_move_2': '¡No te muevas! Tomando foto en 2...',
      'selfie_no_move_1': '¡No te muevas! Tomando foto en 1...',
      'selfie_moved': '⚠️ Moviste la cara, vuelve a colocarla',
      'selfie_taking': '📸 Tomando foto...',
      'selfie_ready': '¡Selfie lista!',
      'selfie_error': 'Error al tomar la foto, intenta de nuevo',
      'selfie_no_front_camera': 'No se encontró cámara frontal',
      'selfie_camera_error': 'Error al iniciar la cámara',
      'selfie_auto_detection': 'Detección automática',
      'selfie_retake': 'Repetir',
      'selfie_use': 'Usar esta foto',
      'selfie_not_detected': 'No te detectamos, toca para fotografiar',

      // VerificationPage
      'verify_title': 'Verificación',
      'verify_profile_verified': 'Tu perfil verificado',
      'verify_profile_desc': 'Genera más confianza y consigue más matches',
      'verify_completed': 'de 3 verificaciones completadas',
      'verify_selfie_title': 'Selfie',
      'verify_selfie_subtitle': 'Verifica que eres una persona real',
      'verify_phone_title': 'Teléfono',
      'verify_phone_subtitle': 'Confirma tu número de teléfono',
      'verify_social_title': 'Red social',
      'verify_social_subtitle': 'Vincula tu cuenta de redes sociales',
      'verify_status_verified': 'Verificado',
      'verify_status_pending': 'En revisión',
      'verify_status_none': 'Sin verificar',
      'verify_selfie_sent': 'Selfie enviada',
      'verify_benefits_title': '¿Por qué verificarte?',
      'verify_benefit1_title': 'Más matches',
      'verify_benefit1_desc':
          'Los perfiles verificados reciben hasta 3x más likes',
      'verify_benefit2_title': 'Mayor confianza',
      'verify_benefit2_desc':
          'Los usuarios confían más en perfiles verificados',
      'verify_benefit3_title': 'Destacado en búsquedas',
      'verify_benefit3_desc': 'Aparece antes en los resultados del radar',
      'verify_phone_sheet_title': 'Verificar teléfono',
      'verify_phone_country_label': 'País *',
      'verify_phone_country_hint': 'Selecciona tu país',
      'verify_phone_number_label': 'Número de teléfono *',
      'verify_phone_number_hint': '123 456 7890',
      'verify_send_btn': 'Enviar para verificación',
      'verify_country_picker_title': 'Selecciona tu país',
      'verify_country_search_hint': 'Buscar país...',
      'verify_social_sheet_title': 'Verificar red social',
      'verify_social_network_label': 'Red social',
      'verify_username_label': 'Nombre de usuario',
      'verify_username_hint': '@tuusuario',
      'verify_url_generated': 'URL generada',
      'verify_view_profile': 'Ver perfil',
      'verify_view_profile_hint':
          'Toca "Ver perfil" para confirmar que es tu cuenta',
      'verify_selfie_sheet_title': 'Verificar con selfie',
      'verify_profile_photo_label': 'Tu foto de perfil',
      'verify_selfie_label': 'Tu selfie',
      'verify_add_photo': 'Agregar foto',
      'verify_photo_required': 'Requerida para la selfie',
      'verify_change_photo': 'Cambiar',
      'verify_take_selfie': 'Tomar selfie',
      'verify_retake': 'Tomar otra',
      'verify_selfie_info':
          'Asegúrate de que tu rostro sea claramente visible y coincida con tu foto de perfil.',
      'verify_send_selfie': 'Enviar selfie',

      'verify_load_error': 'No se pudieron cargar las verificaciones',
      'verify_phone_empty': 'Ingresa tu número de teléfono',
      'verify_country_empty': 'Selecciona tu país',
      'verify_phone_success': 'Teléfono enviado para verificación',
      'verify_username_empty': 'Ingresa tu nombre de usuario primero',
      'verify_url_error': 'La URL no se pudo generar',
      'verify_social_success': 'Red social enviada para verificación',
      'verify_browser_error': 'No se pudo abrir el navegador',
      'verify_selfie_empty': 'Toma una selfie primero',
      'verify_no_profile_photo': 'No tienes foto de perfil configurada',
      'verify_selfie_success': 'Selfie enviada para verificación',

      'verify_gate_title': 'Verifica tu perfil para usar el radar',
      'verify_gate_desc':
          'Necesitas completar todas las verificaciones antes de buscar personas cercanas.',
      'verify_gate_btn': 'Verificar mi perfil',
      'verify_gate_not_verified': 'Sin verificar',

      //cupon google
      'purchase_title': 'Adquirir Créditos',
      'purchase_subtitle':
          'Agrega créditos a tu cuenta y desbloquea más conexiones.',
      'purchase_payment_method': 'Método de pago:',
      'purchase_buy_btn': 'Comprar',
      'purchase_empty_title': 'Sin productos disponibles',
      'purchase_retry': 'Reintentar',
      'purchase_coupon_label': 'Cupón de descuento (opcional)',
      'purchase_coupon_hint': 'Ej: DESCUENTO20',
      'purchase_coupon_applied': 'Cupón aplicado al realizar la compra',
      'purchase_credits': 'créditos',
      'purchase_no_device': 'Compras no disponibles en este dispositivo',
      'purchase_in_progress': 'Ya hay una compra en progreso',
      'purchase_product_not_found': 'Producto no encontrado en la tienda',
      'purchase_load_error': 'Error al cargar los productos',
      'purchase_error': 'Error al iniciar la compra',
      'purchase_stream_error': 'Error en el proceso de compra',
      'purchase_processing': 'Procesando compra...',
      'purchase_canceled': 'Compra cancelada',
      'purchase_verify_error': 'Error al verificar la compra con el servidor',
      'purchase_internal_error': 'Error interno al procesar la compra',
      'purchase_success': '¡Compra completada exitosamente!',
      'purchase_appstore': 'App Store',
      'purchase_googleplay': 'Google Play',
      'coupon_valid': 'Cupón válido',
      'coupon_invalid': 'Código de cupón no válido',
      'coupon_validate_error': 'Error al validar el cupón',
      'coupon_must_validate': 'Valida el cupón antes de continuar',
      'coupon_bonus': 'créditos extra con este cupón',

      //QRScannerWidget
      'qr_scan_title': 'ESCANEAR CUPÓN',
      'qr_scan_description': 'Apunta al código QR del cupón para aplicarlo',
      'qr_scan_default_title': 'ESCANEAR QR',
      'qr_scan_default_description': 'Escanea el código QR',
      'qr_scan_instruction':
          'Coloca el código QR dentro del marco y mantén estable el dispositivo',
      'qr_scan_torch_off': 'Apagar',
      'qr_scan_torch_on': 'Linterna',
      'qr_scan_switch_camera': 'Cambiar',
      'qr_scan_cancel': 'CANCELAR ESCANEO',
      'qr_scan_restart_camera': 'Reiniciar cámara',
      'qr_scan_camera_error': 'Error de cámara',
    },
    'Inglés': {
      // ── UpdateProfilePage ──────────────────────────
      'age_range': 'Age Range',
      'max_distance': 'Max Distance',
      'height': 'Height',
      'my_gender': 'My Gender',
      'language': 'Language',
      'birth_date': 'Date of Birth',
      'looking_for': 'Looking for',
      'connection_type': 'Connection Type',
      'delete_account': 'Delete Account',
      'no_limit': 'No limit',
      "bs_no_numbers": "cannot contain numbers",

      // ── ProfilePage ────────────────────────────────
      'profile': 'Profile',
      'discover': 'Discover nearby profiles',
      'photos': 'Photos',
      'photos_hint': 'Tap + to add multiple photos at once',
      'my_biography': 'My Biography',
      'add_status': 'Add status',

      // ── LikedByUsersView ───────────────────────────
      'pending_chats': 'Pending Match',
      'unlock_hint': 'Unlock chats to start chatting.',
      'unlock': 'Unlock',
      'connect': 'Connect',

      // ── RadarScannerScreen ─────────────────────────
      'searching': 'Looking for connections...',
      'nearby': 'Profiles near you',
      'search_btn': 'Find Nearby Profiles',
      'view_profile': 'View my profile',
      'travel_mode_active': 'Travel mode active',
      'travel_mode_active_desc': 'You\'re viewing profiles from another city',
      'travel_mode_deactivated': 'Travel mode deactivated',
      'deactivate': 'Deactivate',
      'search_city_title': 'Search city',
      'search_city_hint': 'Type a city name...',
      'search_city_prompt': 'Type to search cities',
      'search_city_no_results': 'No results found',
      'search_city_btn': 'Search in another city',
      'city_updated': 'City updated',
      // ── MyMatchView ────────────────────────────────
      'stories': 'Stories',
      'my_story': 'My story',
      'chats': 'Chats',
      'no_reply': 'No reply',
      'filter_chats': 'Filter chats',
      'filter_no_reply': 'No reply',
      'filter_no_reply_desc': 'Only chats waiting for your reply',
      'clear_filters': 'Clear filters',
      'search_hint': 'Search chats...',
      'your_turn': 'Your turn',
      'start_chat': 'Start chatting!',
      'all_caught_up': 'All caught up! No pending chats',
      'see_all': 'See all chats',

      // ── InterestsSectionWidget ─────────────────────
      'interests_title': 'Interests',
      'interests_subtitle': 'Show the things you love',
      'interests_add': 'Add your interests',

      // ── QualitiesSectionWidget ─────────────────────
      'qualities_title': 'Qualities I value',
      'qualities_subtitle': 'Choose up to 3 qualities you value in a person.',
      'qualities_add': 'Add qualities you value',

      // ── Bottom sheets: Intereses ───────────────────
      'bs_interests_title': 'Choose your main\ninterests',
      'bs_interests_subtitle': 'Your interests help us find better matches.',
      'bs_interests_counter': 'Popular interests',
      'bs_interests_selected': 'selected',
      'bs_max_interests': 'You can select up to 5 interests',
      'bs_interests_saved': 'Interests updated successfully',
      'bs_interests_load_error': 'Could not load interests',

      // ── Bottom sheets: Cualidades ──────────────────
      'bs_qualities_title': 'What you appreciate most\nin a person',
      'bs_qualities_subtitle': 'These qualities help us create better matches.',
      'bs_qualities_counter': 'What you look for in someone',
      'bs_max_qualities': 'You can select up to 3 qualities',
      'bs_qualities_saved': 'Qualities updated successfully',

      // ── Bottom sheets: Altura ──────────────────────
      'bs_height_title': 'Your height',
      'bs_height_subtitle': 'This information helps us improve your matches.',

      // ── Bottom sheets: Género ──────────────────────
      'bs_gender_title': 'What is your gender?',
      'bs_gender_subtitle': 'This information can be edited later.',

      // ── Bottom sheets: Idioma ──────────────────────
      'bs_language_title': 'Your main language',
      'bs_language_subtitle': 'You can adjust this later.',

      // ── Bottom sheets: Fecha nacimiento ───────────
      'bs_dob_title': 'Date of birth',
      'bs_dob_subtitle': 'You must be over 18 years old.',
      'bs_dob_age_error': 'You must be at least 18 years old to register.',

      // ── Bottom sheets: Busco ───────────────────────
      'bs_search_gender_title': 'What kind of people would\nyou like to meet?',
      'bs_search_gender_subtitle':
          'This preference is flexible and editable later.',

      // ── Bottom sheets: Tipo de conexión ───────────
      'bs_connection_title': 'What kind of connection\ndo you want?',
      'bs_connection_subtitle': 'Select the option that suits you.',

      // ── Bottom sheets: Rango de edad ──────────────
      'bs_age_range_title': 'Age range',
      'bs_age_min': 'Minimum',
      'bs_age_max': 'Maximum',

      // ── Bottom sheets: Distancia ───────────────────
      'bs_distance_title': 'Max distance',
      'bs_no_limit_distance': 'Max distance',

      // ── Bottom sheets: Biografía ───────────────────
      'bs_bio_title': 'Tell us about yourself',
      'bs_bio_subtitle': 'A good biography helps generate better connections.',
      'bs_bio_hint': 'Write something about yourself...',

      // ── Bottom sheets: Estado ──────────────────────
      'bs_status_title': 'Your status',
      'bs_status_subtitle': 'A short status that reflects how you feel today.',
      'bs_status_hint': 'E.g: Looking for adventures...',

      // ── Snackbars generales ────────────────────────
      'snack_no_changes': 'No new changes',
      'snack_updated': 'Updated successfully',
      'snack_height_saved': 'Height updated',
      'snack_gender_saved': 'Gender updated',
      'snack_language_saved': 'Language updated',
      'snack_dob_saved': 'Date of birth updated',
      'snack_search_gender_saved': 'Preference updated',
      'snack_connection_saved': 'Connection type updated',
      'snack_age_range_saved': 'Age range updated',
      'snack_distance_saved': 'Distance updated',
      'snack_bio_saved': 'Biography updated',
      'snack_status_saved': 'Status updated',
      'snack_interest_removed': 'Interest removed successfully',
      'snack_quality_removed': 'Quality removed successfully',
      'snack_photo_added': 'Your photo has been added successfully',
      'snack_photo_removed': 'Photo removed successfully',
      'snack_could_not_update': 'Could not update',
      'snack_could_not_delete': 'Could not delete',
      'snack_could_not_save_interests': 'Could not save interests',
      'snack_could_not_save_qualities': 'Could not save qualities',

      // ── Alertas generales ──────────────────────────
      'alert_delete_photo_title': 'Delete photo',
      'alert_delete_photo_msg': 'Are you sure you want to delete this photo?',
      'alert_logout_title': 'Log out',
      'alert_logout_msg': 'Are you sure you want to log out?',
      'alert_delete_account_title': 'Delete account',
      'alert_delete_account_msg':
          'Are you sure? This action is permanent and cannot be undone.',
      'alert_confirm': 'Accept',
      'alert_delete': 'Delete',

      // ── Compartidas ────────────────────────────────
      'years': 'years',
      'user': 'User',
      'loading': 'Loading...',
      'loading_chats': 'Loading chats...',
      'loading_pending': 'Loading pending chats...',
      'error_title': 'Error loading chats',
      'retry': 'RETRY',
      'empty_title_chats': 'No chats yet',
      'empty_subtitle_chats':
          'Start liking profiles to find your perfect match',
      'empty_title_pending': 'No pending match',
      'empty_subtitle_pending':
          'When someone writes to you, it will appear here',
      'explore': 'EXPLORE PROFILES',
      'save': 'Save',
      'cancel': 'Cancel',
      'error': 'Error',
      'accept': 'Accept',
      'no_more_profiles': 'No more profiles',
      'no_more_profiles_desc':
          'We couldn\'t find profiles matching your current filters. Expand your search range to see more people.',
      'modify_preferences': 'Modify preferences',
      'try_again': 'Try again',
      // ── RegisterPage ───────────────────────────────
      'register_title': 'Get Started',
      'register_have_account': 'Already have an account? ',
      'register_login': 'Log In',
      'register_name': 'Full Name:',
      'register_name_hint': 'Karen Hernández Costa',
      'register_email': 'Email:',
      'register_email_hint': 'email@gmail.com',
      'register_password': 'Create a password',
      'register_confirm_password': 'Confirm your password:',
      'register_privacy':
          'By registering you accept the Privacy Policy and Terms & Conditions.',
      'register_btn': 'Register',

      'personal_title': 'Let\'s start with\nthe basics',
      'personal_dob': 'Select your date of birth',
      'personal_dob_placeholder': '14/05/1993',
      'personal_gender': 'How do you identify?',
      'personal_bio': 'Tell us about yourself:',
      'personal_bio_hint': 'Write a short biography...',

      'physical_title': 'This information helps us\nimprove your matches',
      'physical_height': 'Your height',

      'interests_page_title': 'Choose your main\ninterests',
      'interests_page_subtitle': 'Your interests help us find better\nmatches.',
      'interests_search_hint': 'Search interests',
      'interests_popular': 'Popular interests',
      'interests_custom_hint': 'If you can\'t find your results, write them...',

      'qualities_page_title': 'What you appreciate most\nin a person',
      'qualities_page_subtitle':
          'These qualities help us create better matches.',
      'qualities_counter_label': 'What you look for in someone',

      'nav_skip': 'Skip',
      'login_title': 'Log In',
      'login_no_account': 'Don\'t have an account yet? ',
      'login_register': 'Register',
      'login_email': 'Email:',
      'login_email_hint': 'email@gmail.com',
      'login_password': 'Password:',
      'login_remember': 'Remember me',
      'login_btn': 'Log In',
      'login_forgot': 'Forgot your password?',
      'forgot_title': 'Recover your password',
      'forgot_step1': "Enter your email and we'll send you a 6-digit code.",
      'forgot_step2': 'Check your email, enter the code and choose a new password.',
      'forgot_code': 'Code',
      'forgot_new_password': 'New password',
      'forgot_send_btn': 'Send code',
      'forgot_change_btn': 'Change password',
      'forgot_resend': 'Resend code',
      'forgot_code_sent': 'If the email exists, we sent you a code',
      'forgot_done': 'Password updated. You can log in now',
      'forgot_err_email': 'Enter a valid email',
      'forgot_err_code': 'The code has 6 digits',
      'forgot_err_password': 'Password must be at least 8 characters',
      'val_name_required': 'Name is required',
      'val_name_min': 'Minimum 3 characters',
      'val_email_required': 'Email is required',
      'val_email_invalid': 'Enter a valid email',
      'val_password_required': 'Password is required',
      'val_min_8': 'Minimum 8 characters',
      'val_min_10': 'Minimum 10 characters',
      'val_max_500': 'Maximum 500 characters',
      'val_passwords_no_match': 'Passwords do not match',
      'val_dob_required': 'Select your date of birth',
      'val_gender_required': 'Select your gender',
      'val_custom_gender_required': 'Write how you identify',
      'val_bio_required': 'Biography is required',
      'val_bio_min': 'Biography must have at least 10 characters',
      'val_bio_max': 'Biography must have at most 500 characters',
      'val_height_required': 'Enter your height',
      'val_height_invalid': 'Enter a valid height between 100 and 250 cm',
      'val_interest_required': 'Select at least one interest',
      'val_max_interests': 'You can only select up to',
      'val_max_qualities': 'You can only select up to',
      'register_success': 'Registration successful. Please log in.',
      'login_warning': 'Warning',
      'login_val_email': 'Please enter your email',
      'login_val_password': 'Please enter your password',
      'login_error_title': 'Incorrect access',
      'chat_reconnecting': 'Reconnecting...',
      'chat_no_connection': 'No connection · Tap to retry',
      'chat_cost_info': 'This message costs ',
      'chat_balance_info': 'Your current credits are ',
      'chat_charge_info': 'The message will be charged only when sent.',
      'chat_first_msg_sent': 'First message sent. Wait for a reply.',
      'followers': 'followers',
      'following': 'following',
      'follow_btn': 'Follow',
      'following_btn': 'Following',
      'feed_title': 'Feed',
      'feed_new_post': 'Post',
      'feed_write': 'What do you want to share?',
      'feed_publish': 'Post',
      'feed_add_photo': 'Photos',
      'feed_add_video': 'Video',
      'feed_comments': 'Comments',
      'feed_comment_hint': 'Write a comment…',
      'feed_reply': 'Reply',
      'feed_replying_to': 'Replying to',
      'feed_delete': 'Delete',
      'feed_report': 'Report',
      'feed_reported': 'Thanks, we will review this content',
      'feed_deleted': 'Post deleted',
      'feed_video_too_long': 'Video must be 60 seconds or less',
      'feed_video_too_big': 'Video must be 50 MB or less',
      'feed_max_media': 'Maximum 10 files per post',
      'feed_user_posts': 'Posts',
      'feed_no_comments': 'Be the first to comment',
      'feed_react': 'React',
      'feed_confirm_delete': 'Delete this post?',
      'feed_load_more': 'Load more',
      'feed_retry': 'Retry',
      'feed_empty_title': 'Your feed is empty',
      'feed_empty': 'Follow people to see what they share, or share something yourself.',
      'feed_empty_user': 'No posts yet',
      'feed_discover': 'Discover people',
      'feed_create_first': 'Create my first post',
      'feed_see_more': 'more',
      'feed_view_all': 'View all',
      'feed_view_one': 'View 1 comment',
      'feed_audience': 'Your followers',
      'feed_create_title': 'New post',
      'gift_send_title': 'Send a gift',
      'gift_to': 'to',
      'gift_send_btn': 'Send',
      'gift_credits': 'credits',
      'gift_pick': 'Pick a gift',
      'gift_recharge': 'Get more credits',
      'gift_sent': 'Gift sent!',
      'gift_pill': 'Gift',
      'gift_received_title': 'Gifts received',
      'gift_you_sent': 'You sent a gift',
      'gift_sent_to_you': 'Sent you a gift',
      'plans_title': 'Plans',
      'my_credits': 'My credits',
      'chat_online': 'Online',
      'chat_last_seen': 'Last seen',
      'profile_posts_short': 'Posts',
      'gift_recharge_short': 'Top up',
      'profile_followers': 'Followers',
      'profile_following': 'Following',
      'profile_gifts': 'Gifts',
      'profile_connections': 'Connections',
      'profile_no_posts': 'No posts yet',
      'profile_no_posts_own': 'You have not posted anything yet. Share your first photo or thought!',
      'profile_no_plans': 'No plans for now',
      'profile_no_plans_own': 'You have no plans yet. Create one or join one.',
      'profile_no_communities': 'Not in any public community',
      'profile_no_communities_own': 'You have not joined any community yet',
      'profile_no_gifts': 'Has not received gifts yet',
      'profile_no_gifts_own': 'You have not received gifts yet',
      'profile_see_all_posts': 'See all posts',
      'profile_see_all_plans': 'See all my plans',
      'follow_list_empty_followers': 'No followers yet',
      'follow_list_empty_following': 'Not following anyone yet',
      'feed_filter_communities': 'Communities',
      'community_my': 'My communities',
      'community_new': 'New',
      'community_empty': 'No communities yet. Create the first one and bring your people together!',
      'community_create': 'Create community',
      'community_create_btn': 'Create community',
      'community_f_name': 'Community name',
      'community_f_name_hint': 'E.g. Hiking lovers',
      'community_f_description_hint': 'What it is about and what the rules are…',
      'community_f_city': 'City (optional)',
      'community_f_city_hint': 'E.g. Guadalajara',
      'community_private': 'Private community',
      'community_private_hint': 'People join with your approval and only members see the content',
      'community_public_hint': 'Anyone can join and see the content',
      'community_add_cover': 'Add cover',
      'community_err_name': 'The name must have at least 3 letters',
      'community_members': 'Members',
      'community_joined': 'Member',
      'community_role_admin': 'Admin',
      'community_role_moderator': 'Moderator',
      'community_locked': 'This community is private. Request to join to see its posts and members.',
      'community_no_posts': 'No posts yet. Be the first to post!',
      'community_no_requests': 'No pending requests',
      'community_make_admin': 'Make admin',
      'community_make_moderator': 'Make moderator',
      'community_make_member': 'Remove role',
      'community_kick': 'Remove from community',
      'community_leave': 'Leave community',
      'community_post_here': 'Post in the community',
      'community_post_in': 'Post in',
      'community_delete': 'Delete community',
      'community_delete_confirm': 'Delete this community?',
      'community_delete_hint': 'The community and all its posts will be hidden. This cannot be undone.',
      'community_cat_gaming': 'Gaming',
      'community_cat_fitness': 'Fitness',
      'community_cat_viajes': 'Travel',
      'community_cat_musica': 'Music',
      'community_cat_deportes': 'Sports',
      'community_cat_fotografia': 'Photography',
      'community_cat_cocina': 'Cooking',
      'community_cat_arte': 'Art',
      'community_cat_tecnologia': 'Technology',
      'community_cat_local': 'Local',
      'community_cat_otro': 'Other',
      'feed_filter_all': 'All',
      'feed_filter_posts': 'Posts',
      'feed_filter_plans': 'Plans',
      'plans_discover': 'Discover',
      'plans_mine': 'My plans',
      'plans_create': 'Create plan',
      'plans_all': 'All',
      'plans_empty_discover': 'No upcoming plans yet. Create the first one!',
      'plans_empty_mine': 'You have no plans yet. Join one or create your own.',
      'plans_upcoming': 'Upcoming',
      'plans_past': 'Past',
      'plan_months': 'Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec',
      'plan_weekdays': 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
      'plan_cat_salidas': 'Outings',
      'plan_cat_cine': 'Movies',
      'plan_cat_senderismo': 'Hiking',
      'plan_cat_viajes': 'Travel',
      'plan_cat_deportes': 'Sports',
      'plan_cat_gaming': 'Gaming',
      'plan_cat_restaurantes': 'Restaurants',
      'plan_cat_conciertos': 'Concerts',
      'plan_cat_reuniones': 'Meetups',
      'plan_cat_social': 'Social',
      'plan_cat_otro': 'Other',
      'plan_cancelled': 'Plan cancelled',
      'plan_going': 'going',
      'plan_yours': 'Your plan',
      'plan_you_go': 'You are going',
      'plan_pending': 'Pending',
      'plan_full': 'Full',
      'plan_cancel_confirm': 'Cancel this plan?',
      'plan_cancel_hint': 'Everyone who joined will be notified.',
      'plan_cancel_action': 'Cancel plan',
      'plan_needs_approval': 'Approval required',
      'plan_needs_approval_hint': 'You decide who joins',
      'plan_open': 'Open to everyone',
      'plan_organizer': 'Hosted by',
      'plan_going_title': 'Going',
      'plan_requests': 'Requests',
      'plan_finished': 'This plan has ended',
      'plan_leave': 'Leave plan',
      'plan_cancel_request': 'Cancel request',
      'plan_rejected': 'Request not accepted',
      'plan_request': 'Request to join',
      'plan_join': 'Join',
      'plan_f_title': 'Plan name',
      'plan_f_title_hint': 'E.g. Movie night',
      'plan_f_category': 'Category',
      'plan_f_when': 'When',
      'plan_f_date': 'Date',
      'plan_f_time': 'Time',
      'plan_f_place': 'Place',
      'plan_f_place_hint': 'E.g. Downtown cinema',
      'plan_use_location': 'Use my current location',
      'plan_f_description': 'Description',
      'plan_f_description_hint': 'Tell people what the plan is about…',
      'plan_f_capacity': 'Capacity',
      'plan_unlimited': 'No limit of people',
      'plan_f_capacity_hint': 'Maximum people (2 to 500)',
      'plan_publish': 'Publish plan',
      'plan_add_cover': 'Add cover',
      'plan_location_denied': 'Location permission denied',
      'plan_location_set': 'Location added',
      'plan_err_title': 'Write a name for the plan (at least 3 letters)',
      'plan_err_datetime': 'Pick a date and time',
      'plan_err_place': 'Tell us where the plan is',
      'plan_err_future': 'Date and time must be in the future',
      'plan_err_capacity': 'Capacity must be between 2 and 500 people',
      'chat_hint_blocked': 'Waiting for reply...',
      'chat_hint': 'Write a message...',
      'chat_empty_title': 'Start the conversation',
      'chat_empty_subtitle': 'Send the first message to begin',
      'chat_error_title': 'Error loading messages',
      'nearby_no_more': 'No more nearby users',
      'nearby_load_error': 'Could not load users',
      'nearby_liked': 'You like',
      'nearby_removed_fav': 'removed from favorites',
      'nearby_error_process': 'Error processing',
      'nearby_like_sent': 'You liked',
      'nearby_error_like': 'Error liking',
      'nearby_next_profile': 'Moving to next profile',
      'nearby_error_reject': 'Error rejecting',
      'nearby_superlike_sent': 'You sent a Super Like to',
      'nearby_block_title': 'Block user',
      'nearby_block_msg': 'Are you sure you want to block',
      'nearby_block_confirm': 'Block',
      'nearby_blocked': 'has been blocked',
      'nearby_all_seen': 'You have seen all available profiles',
      'nearby_report_title': 'Report user',
      'nearby_report_msg': 'Why do you want to report',
      'nearby_report_confirm': 'Report',
      'nearby_report_thanks':
          'Thanks for your report. We will review the profile of',
      'nearby_send_message': 'Send message',
      'nearby_view_profile': 'View full profile', 'chat_credits': 'credits',
      'location_required_title': 'Location required',
      'location_required_desc':
          'We need your location to show you nearby users',
      'enable_location': 'Enable location',
      'open_settings': 'Open settings',
      //PreferencesPage
      'pref_gender_title': 'What kind of people would\nyou like to meet?',
      'pref_gender_subtitle': 'This preference is flexible and editable later.',
      'pref_gender_hint':
          'We\'ll show you profiles compatible with your preferences.',
      'pref_connection_title': 'What kind of connection\ndo you want?',
      'pref_connection_subtitle': 'Select up to two options that suit you.',
      'pref_connection_hint':
          'We\'ll show this preference to improve your matches.',
      'pref_age_title': 'What age range\ndo you prefer?',
      'pref_age_subtitle': 'You can adjust this later.',
      'pref_distance_title': 'Max distance',
      'pref_distance_up_to': 'Up to',
      'pref_photos_title': 'Introduce yourself with photos',
      'pref_photos_subtitle':
          'Upload at least 2 photos that show your essence.\nThe best connections start with great photos.',
      'pref_selection_required': 'Selection required',
      'pref_select_gender': 'Select a type of person',
      'pref_select_connection': 'Select at least one connection type',
      'pref_invalid_range': 'Invalid range',
      'pref_age_range_error': 'Minimum age cannot be greater than maximum age',
      'pref_photos_required': 'Photos required',
      'pref_photos_min': 'You must upload at least 2 photos',
      'pref_interests_required': 'Interests required',
      'pref_qualities_required': 'Qualities required',
      'pref_select_quality': 'You must select at least one quality',
      'pref_limit_reached': 'Limit reached',

      'pref_no_interests': 'No interests available',
      'pref_no_qualities': 'No qualities available',

      'pref_photos_max': 'You can upload up to',
      'pref_photos_partial': 'Only',
      'pref_photos_pick_error': 'Could not select photo',
      'pref_photo_take_error': 'Could not take photo',
      'pref_add_photos': 'Add photos',
      'pref_gallery_multiple': 'Gallery (multiple selection)',
      'pref_gallery_multiple_hint': 'Select several photos at once',
      'pref_take_photo': 'Take photo',
      'pref_take_photo_hint': 'Capture a new photo',
      // ── Tutoriales ─────────────────────────────────
      'tutorial_start_profile':
          'Here you can view and edit your profile information',
      'tutorial_start_radar': 'Radar: find people near your location',
      'tutorial_start_match': 'Match: see people who want to connect with you',
      'tutorial_start_chat':
          'Chat: continue conversations with your connections',
      'tutorial_start_panic':
          'Panic button: in an emergency, press it to call 911 and get immediate help',

      'tutorial_profile_blocked':
          'Here you can view and manage users you have blocked',
      'tutorial_profile_notifications':
          'Manage your push notifications and alert preferences',
      'tutorial_profile_edit':
          'Edit your profile: name, age, preferences and more',
      'tutorial_profile_settings': 'option to log out',
      'tutorial_profile_credits':
          'Tap here to add more credits to your account',
      'tutorial_profile_status':
          'Tap to edit your status message visible on the radar',

      'tutorial_update_age':
          'Edit the age range of people you prefer to connect with',
      'tutorial_update_distance':
          'Adjust the maximum distance of people you prefer to connect with',

      'tutorial_radar_slider':
          'Adjust the search radius to find people closer or farther from you',
      'tutorial_radar_points':
          'We give you a small group of nearby profiles so you can see each person',
      'tutorial_radar_search': 'Tap again to see more',
      'tutorial_radar_profile': 'Tap to view profiles',
      'tutorial_skip': 'Skip',
      // ── LikedByUsersView ───────────────────────────
      'liked_by_title': 'They liked me',
      'liked_by_hint': 'Users who liked you',
      'liked_by_tab': 'Liked me',
      'pending_tab': 'Pending',
      'liked_by_view_profile': 'View profile',
      'liked_by_empty_title': 'Nobody has liked you yet',
      'liked_by_empty_subtitle': 'Keep exploring to get more matches',
      'liked_by_error_title': 'Error loading likes',
      'liked_by_loading': 'Loading likes...',

      //reportar
      'report_title': 'Report',
      'report_select_reason': 'Select the reason for the report',
      'report_harassment': 'Harassment or intimidation',
      'report_inappropriate': 'Inappropriate content',
      'report_fake': 'Fake profile or spam',
      'report_offensive': 'Offensive behavior',
      'report_minor': 'Minor',
      'report_other': 'Other',
      'report_desc_hint': 'Description (required)',
      'report_desc_required': 'Description is required',
      'report_also_block': 'Also block',
      'report_block_hint':
          'They won\'t be able to contact you or see your profile',
      'report_send': 'Send report',
      'report_send_and_block': 'Report and block',
      'report_success': 'Report sent. We will review the profile of',
      'report_block_success': 'has been reported and blocked',
      //SelfieCameraResult
      'selfie_place_face': 'Place your face in the circle',
      'selfie_face_detected': 'Face detected, stay still...',
      'selfie_no_move_3': 'Don\'t move! Taking photo in 3...',
      'selfie_no_move_2': 'Don\'t move! Taking photo in 2...',
      'selfie_no_move_1': 'Don\'t move! Taking photo in 1...',
      'selfie_moved': '⚠️ You moved, place your face again',
      'selfie_taking': '📸 Taking photo...',
      'selfie_ready': 'Selfie ready!',
      'selfie_error': 'Error taking photo, try again',
      'selfie_no_front_camera': 'Front camera not found',
      'selfie_camera_error': 'Error starting camera',
      'selfie_auto_detection': 'Automatic detection',
      'selfie_retake': 'Retake',
      'selfie_use': 'Use this photo',
      'selfie_not_detected': 'We can\'t detect you, tap to take photo',

      // VerificationPage
      'verify_title': 'Verification',
      'verify_profile_verified': 'Your verified profile',
      'verify_profile_desc': 'Build trust and get more matches',
      'verify_completed': 'of 3 verifications completed',
      'verify_selfie_title': 'Selfie',
      'verify_selfie_subtitle': 'Verify you are a real person',
      'verify_phone_title': 'Phone',
      'verify_phone_subtitle': 'Confirm your phone number',
      'verify_social_title': 'Social network',
      'verify_social_subtitle': 'Link your social media account',
      'verify_status_verified': 'Verified',
      'verify_status_pending': 'Under review',
      'verify_status_none': 'Not verified',
      'verify_selfie_sent': 'Selfie sent',
      'verify_benefits_title': 'Why verify yourself?',
      'verify_benefit1_title': 'More matches',
      'verify_benefit1_desc': 'Verified profiles get up to 3x more likes',
      'verify_benefit2_title': 'More trust',
      'verify_benefit2_desc': 'Users trust verified profiles more',
      'verify_benefit3_title': 'Featured in searches',
      'verify_benefit3_desc': 'Appear first in radar results',
      'verify_phone_sheet_title': 'Verify phone',
      'verify_phone_country_label': 'Country *',
      'verify_phone_country_hint': 'Select your country',
      'verify_phone_number_label': 'Phone number *',
      'verify_phone_number_hint': '123 456 7890',
      'verify_send_btn': 'Send for verification',
      'verify_country_picker_title': 'Select your country',
      'verify_country_search_hint': 'Search country...',
      'verify_social_sheet_title': 'Verify social network',
      'verify_social_network_label': 'Social network',
      'verify_username_label': 'Username',
      'verify_username_hint': '@yourusername',
      'verify_url_generated': 'Generated URL',
      'verify_view_profile': 'View profile',
      'verify_view_profile_hint':
          'Tap "View profile" to confirm it\'s your account',
      'verify_selfie_sheet_title': 'Verify with selfie',
      'verify_profile_photo_label': 'Your profile photo',
      'verify_selfie_label': 'Your selfie',
      'verify_add_photo': 'Add photo',
      'verify_photo_required': 'Required for selfie',
      'verify_change_photo': 'Change',
      'verify_take_selfie': 'Take selfie',
      'verify_retake': 'Take another',
      'verify_selfie_info':
          'Make sure your face is clearly visible and matches your profile photo.',
      'verify_send_selfie': 'Send selfie',
      'verify_load_error': 'Could not load verifications',
      'verify_phone_empty': 'Enter your phone number',
      'verify_country_empty': 'Select your country',
      'verify_phone_success': 'Phone sent for verification',
      'verify_username_empty': 'Enter your username first',
      'verify_url_error': 'URL could not be generated',
      'verify_social_success': 'Social network sent for verification',
      'verify_browser_error': 'Could not open browser',
      'verify_selfie_empty': 'Take a selfie first',
      'verify_no_profile_photo': 'You have no profile photo set',
      'verify_selfie_success': 'Selfie sent for verification',
      'verify_gate_title': 'Verify your profile to use the radar',
      'verify_gate_desc':
          'You need to complete all verifications before searching for nearby people.',
      'verify_gate_btn': 'Verify my profile',
      'verify_gate_not_verified': 'Not verified',

      //cupon google
      'purchase_title': 'Get Credits',
      'purchase_subtitle':
          'Add credits to your account and unlock more connections.',
      'purchase_payment_method': 'Payment method:',
      'purchase_buy_btn': 'Buy',
      'purchase_empty_title': 'No products available',
      'purchase_retry': 'Retry',
      'purchase_coupon_label': 'Discount coupon (optional)',
      'purchase_coupon_hint': 'Ex: DISCOUNT20',
      'purchase_coupon_applied': 'Coupon will be applied at checkout',
      'purchase_credits': 'credits',
      'purchase_no_device': 'Purchases not available on this device',
      'purchase_in_progress': 'A purchase is already in progress',
      'purchase_product_not_found': 'Product not found in the store',
      'purchase_load_error': 'Error loading products',
      'purchase_error': 'Error starting purchase',
      'purchase_stream_error': 'Error during purchase process',
      'purchase_processing': 'Processing purchase...',
      'purchase_canceled': 'Purchase canceled',
      'purchase_verify_error': 'Error verifying purchase with server',
      'purchase_internal_error': 'Internal error processing purchase',
      'purchase_success': 'Purchase completed successfully!',
      'purchase_appstore': 'App Store',
      'purchase_googleplay': 'Google Play',
      'coupon_valid': 'Valid coupon',
      'coupon_invalid': 'Invalid coupon code',
      'coupon_validate_error': 'Error validating coupon',
      'coupon_must_validate': 'Validate the coupon before continuing',
      'coupon_bonus': 'extra credits with this coupon',

      //QRScannerWidget
      'qr_scan_title': 'SCAN COUPON',
      'qr_scan_description': 'Point at the coupon QR code to apply it',
      'qr_scan_default_title': 'SCAN QR',
      'qr_scan_default_description': 'Scan the QR code',
      'qr_scan_instruction':
          'Place the QR code inside the frame and keep the device steady',
      'qr_scan_torch_off': 'Turn off',
      'qr_scan_torch_on': 'Torch',
      'qr_scan_switch_camera': 'Switch',
      'qr_scan_cancel': 'CANCEL SCAN',
      'qr_scan_restart_camera': 'Restart camera',
      'qr_scan_camera_error': 'Camera error',
    },
  };
}
